### PR TITLE
working on Win 10 ..

### PR DESCRIPTION
**Pull request by cloned2k16**
I did get it ''building'' on win10 by just changing these few things ..

( AndroidStudio 3.2.1 )

### CODE REVIEW

**Comment by GeoffreyMetais** [comment]
The only possible relevant change in this is the one concerning mavenCentral(), but I don't get why WIndows wouldn't see the correct repos.
Looks like a setup issue.

**Comment by cloned2k16** [comment]
latest Android studio, using older projects 
often complains about that , the other relevant change is 
the elimination of 2 symbolic links .. 

anyway , this was mostly to save time to others trying to compile it on windows ...  
not really intended as someting relevant :)

**Comment by cloned2k16** [comment]
sorry to bother you , 
(and this is not the place ... but don't know wher to post it (there's no Isssues session here)

I have been spending all day trying to get VLC compiled but there's no chance either in windows or in linux and with different TAGs either ... looks like you either pass a wrong switch or they change the one expected before to switch copilation across ABI .. so nomatter if you compile for ARM or x86 it would always try to compile this part which makes compilation to fail , actually I didn't get a successful compilation using  x86 either cause the other contribs fails ...

------------->>>>>

[  3%] Building C object CMakeFiles/aom_rtcd.dir/aom_dsp/aom_dsp_rtcd.c.o
In file included from /home/paolo/_SRC/vlc-android/vlc/contrib/contrib-android-arm-linux-androideabi/aom/aom_dsp/aom_dsp_rtcd.c:14:
In file included from /home/paolo/_SRC/vlc-android/vlc/contrib/contrib-android-arm-linux-androideabi/aom/aom_build/config/aom_dsp_rtcd.h:1719:
/home/paolo/_SRC/vlc-android/vlc/contrib/contrib-android-arm-linux-androideabi/aom/aom_ports/x86.h:187:3: error: invalid output
      constraint '=a' in asm
  cpuid(0, 0, max_cpuid_val, reg_ebx, reg_ecx, reg_edx);
  ^
/home/paolo/_SRC/vlc-android/vlc/contrib/contrib-android-arm-linux-androideabi/aom/aom_ports/x86.h:58:9: note: expanded from
      macro 'cpuid'
      : "=a"(ax), "=D"(bx), "=c"(cx), "=d"(dx) \
        ^
/home/paolo/_SRC/vlc-android/vlc/contrib/contrib-android-arm-linux-androideabi/aom/aom_ports/x86.h:192:3: error: invalid output
      constraint '=a' in asm
  cpuid(1, 0, reg_eax, reg_ebx, reg_ecx, reg_edx);
  ^
/home/paolo/_SRC/vlc-android/vlc/contrib/contrib-android-arm-linux-androideabi/aom/aom_ports/x86.h:58:9: note: expanded from
      macro 'cpuid'
      : "=a"(ax), "=D"(bx), "=c"(cx), "=d"(dx) \
        ^
/home/paolo/_SRC/vlc-android/vlc/contrib/contrib-android-arm-linux-androideabi/aom/aom_ports/x86.h:215:9: error: invalid output
      constraint '=a' in asm
        cpuid(7, 0, reg_eax, reg_ebx, reg_ecx, reg_edx);
        ^
/home/paolo/_SRC/vlc-android/vlc/contrib/contrib-android-arm-linux-androideabi/aom/aom_ports/x86.h:58:9: note: expanded from
      macro 'cpuid'
      : "=a"(ax), "=D"(bx), "=c"(cx), "=d"(dx) \
        ^
/home/paolo/_SRC/vlc-android/vlc/contrib/contrib-android-arm-linux-androideabi/aom/aom_ports/x86.h:233:38: error: invalid output
      constraint '=a' in asm
  __asm__ __volatile__("rdtsc\n\t" : "=a"(tsc) :);
                                     ^
/home/paolo/_SRC/vlc-android/vlc/contrib/contrib-android-arm-linux-androideabi/aom/aom_ports/x86.h:251:34: error: invalid output
      constraint '=a' in asm
  __asm__ __volatile__("rdtsc" : "=a"(lo), "=d"(hi));
                                 ^
5 errors generated.
make[3]: *** [CMakeFiles/aom_rtcd.dir/aom_dsp/aom_dsp_rtcd.c.o] Error 1
make[3]: Leaving directory `/home/paolo/_SRC/vlc-android/vlc/contrib/contrib-android-arm-linux-androideabi/aom/aom_build'
make[2]: *** [CMakeFiles/aom_rtcd.dir/all] Error 2
make[2]: Leaving directory `/home/paolo/_SRC/vlc-android/vlc/contrib/contrib-android-arm-linux-androideabi/aom/aom_build'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/paolo/_SRC/vlc-android/vlc/contrib/contrib-android-arm-linux-androideabi/aom/aom_build'
make: *** [.aom] Error 2
make: *** Waiting for unfinished jobs....
/home/paolo/_SRC/vlc-android/toolchains/arm/bin/clang -march=armv7-a -mfpu=vfpv3-d16 -mcpu=cortex-a8 -mthumb -mfloat-abi=softfp -MMD -MP -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -fno-integrated-as -I/home/paolo/_SRC/vlc-android/vlc/contrib/arm-linux-androideabi/include -g -O2 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o infback.o infback.c
/home/paolo/_SRC/vlc-android/toolchains/arm/bin/clang -march=armv7-a -mfpu=vfpv3-d16 -mcpu=cortex-a8 -mthumb -mfloat-abi=softfp -MMD -MP -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -fno-integrated-as -I/home/paolo/_SRC/vlc-android/vlc/contrib/arm-linux-androideabi/include -g -O2 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o inffast.o inffast.c
/home/paolo/_SRC/vlc-android/toolchains/arm/bin/clang -march=armv7-a -mfpu=vfpv3-d16 -mcpu=cortex-a8 -mthumb -mfloat-abi=softfp -MMD -MP -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -fno-integrated-as -I/home/paolo/_SRC/vlc-android/vlc/contrib/arm-linux-androideabi/include -g -O2 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o inflate.o inflate.c
/home/paolo/_SRC/vlc-android/toolchains/arm/bin/clang -march=armv7-a -mfpu=vfpv3-d16 -mcpu=cortex-a8 -mthumb -mfloat-abi=softfp -MMD -MP -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -fno-integrated-as -I/home/paolo/_SRC/vlc-android/vlc/contrib/arm-linux-androideabi/include -g -O2 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o inftrees.o inftrees.c
/home/paolo/_SRC/vlc-android/toolchains/arm/bin/clang -march=armv7-a -mfpu=vfpv3-d16 -mcpu=cortex-a8 -mthumb -mfloat-abi=softfp -MMD -MP -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -fno-integrated-as -I/home/paolo/_SRC/vlc-android/vlc/contrib/arm-linux-androideabi/include -g -O2 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o trees.o trees.c
/home/paolo/_SRC/vlc-android/toolchains/arm/bin/clang -march=armv7-a -mfpu=vfpv3-d16 -mcpu=cortex-a8 -mthumb -mfloat-abi=softfp -MMD -MP -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -fno-integrated-as -I/home/paolo/_SRC/vlc-android/vlc/contrib/arm-linux-androideabi/include -g -O2 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o zutil.o zutil.c
/home/paolo/_SRC/vlc-android/toolchains/arm/bin/clang -march=armv7-a -mfpu=vfpv3-d16 -mcpu=cortex-a8 -mthumb -mfloat-abi=softfp -MMD -MP -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -fno-integrated-as -I/home/paolo/_SRC/vlc-android/vlc/contrib/arm-linux-androideabi/include -g -O2 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o compress.o compress.c
/home/paolo/_SRC/vlc-android/toolchains/arm/bin/clang -march=armv7-a -mfpu=vfpv3-d16 -mcpu=cortex-a8 -mthumb -mfloat-abi=softfp -MMD -MP -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -fno-integrated-as -I/home/paolo/_SRC/vlc-android/vlc/contrib/arm-linux-androideabi/include -g -O2 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o uncompr.o uncompr.c
/home/paolo/_SRC/vlc-android/toolchains/arm/bin/clang -march=armv7-a -mfpu=vfpv3-d16 -mcpu=cortex-a8 -mthumb -mfloat-abi=softfp -MMD -MP -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -fno-integrated-as -I/home/paolo/_SRC/vlc-android/vlc/contrib/arm-linux-androideabi/include -g -O2 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o gzclose.o gzclose.c
/home/paolo/_SRC/vlc-android/toolchains/arm/bin/clang -march=armv7-a -mfpu=vfpv3-d16 -mcpu=cortex-a8 -mthumb -mfloat-abi=softfp -MMD -MP -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -fno-integrated-as -I/home/paolo/_SRC/vlc-android/vlc/contrib/arm-linux-androideabi/include -g -O2 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o gzlib.o gzlib.c
/home/paolo/_SRC/vlc-android/toolchains/arm/bin/clang -march=armv7-a -mfpu=vfpv3-d16 -mcpu=cortex-a8 -mthumb -mfloat-abi=softfp -MMD -MP -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -fno-integrated-as -I/home/paolo/_SRC/vlc-android/vlc/contrib/arm-linux-androideabi/include -g -O2 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o gzread.o gzread.c
/home/paolo/_SRC/vlc-android/toolchains/arm/bin/clang -march=armv7-a -mfpu=vfpv3-d16 -mcpu=cortex-a8 -mthumb -mfloat-abi=softfp -MMD -MP -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -fno-integrated-as -I/home/paolo/_SRC/vlc-android/vlc/contrib/arm-linux-androideabi/include -g -O2 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -c -o gzwrite.o gzwrite.c
/home/paolo/_SRC/vlc-android/toolchains/arm/bin/arm-linux-androideabi-ar rc libz.a adler32.o crc32.o deflate.o infback.o inffast.o inflate.o inftrees.o trees.o zutil.o compress.o uncompr.o gzclose.o gzlib.o gzread.o gzwrite.o 
rm -f /home/paolo/_SRC/vlc-android/vlc/contrib/arm-linux-androideabi/lib/libz.a
cp libz.a /home/paolo/_SRC/vlc-android/vlc/contrib/arm-linux-androideabi/lib
chmod 644 /home/paolo/_SRC/vlc-android/vlc/contrib/arm-linux-androideabi/lib/libz.a
rm -f /home/paolo/_SRC/vlc-android/vlc/contrib/arm-linux-androideabi/share/man/man3/zlib.3
cp zlib.3 /home/paolo/_SRC/vlc-android/vlc/contrib/arm-linux-androideabi/share/man/man3
chmod 644 /home/paolo/_SRC/vlc-android/vlc/contrib/arm-linux-androideabi/share/man/man3/zlib.3
rm -f /home/paolo/_SRC/vlc-android/vlc/contrib/arm-linux-androideabi/lib/pkgconfig/zlib.pc
cp zlib.pc /home/paolo/_SRC/vlc-android/vlc/contrib/arm-linux-androideabi/lib/pkgconfig
chmod 644 /home/paolo/_SRC/vlc-android/vlc/contrib/arm-linux-androideabi/lib/pkgconfig/zlib.pc
rm -f /home/paolo/_SRC/vlc-android/vlc/contrib/arm-linux-androideabi/include/zlib.h /home/paolo/_SRC/vlc-android/vlc/contrib/arm-linux-androideabi/include/zconf.h
cp zlib.h zconf.h /home/paolo/_SRC/vlc-android/vlc/contrib/arm-linux-androideabi/include
chmod 644 /home/paolo/_SRC/vlc-android/vlc/contrib/arm-linux-androideabi/include/zlib.h /home/paolo/_SRC/vlc-android/vlc/contrib/arm-linux-androideabi/include/zconf.h
make[1]: Leaving directory `/home/paolo/_SRC/vlc-android/vlc/contrib/contrib-android-arm-linux-androideabi/zlib'
touch .zlib
contribs: make failed

**Comment by GeoffreyMetais** [comment]
VLC-Android build system will shortly be refactored, windows and mac support will be possible right after.
For now I close this PR.

**Pull request closed without merging**
