### PR TITLE
Benchmark: stop samples from appearing in history

### PR DESCRIPTION
**Pull request by Skantes**

### CODE REVIEW

**Comment by GeoffreyMetais** [comment]
Does it erase previously played media from history?

**Comment by Skantes** [comment]
It should not, it's just like deactivating history from the preferences menu. But i'll check tomorrow just to be safe.

**Comment by Skantes** [comment]
It does not erase previously played media from history :+1:

**Comment by GeoffreyMetais** [comment]
Merged in master.
You may have to rewrite it for BenchActivity.java if you want it applied in VLC 3.1

**Pull request closed without merging**
