### PR TITLE
CI with Github actions

### PR DESCRIPTION
**Pull request by hannesa2**
I see you urgent need a CI on each pull request to avoid of new errors.

Currently 
- Espresso can't build
- Unit tests can't build
- Lint has several errors

But step by step and start with this build-only pull request to see if it makes sense to contribute here by merging this first

Btw, I observed this introduce of Github action only starts running on upstream when it's merged. -no clue why-
In my fork it's working even now.. https://github.com/hannesa2/vlc-android/pull/1

### CODE REVIEW

**Comment by GeoffreyMetais** [comment]
Main vlc-android repo is the one on gitlab: https://code.videolan.org/videolan/vlc-android/

So we cannot use Github actions.
Also, we deliberately chose to not include gradlew scripts in our git source code.

**Comment by hannesa2** [comment]
Ok, main repo is on gitlab. 
But that's not smart to have a repo without CI.

This missing gradle makes it not easier. Because someone has fear about the miss-usage of gradle files, but for this I added the gradle verify action. In gitlab you have to do all by yourself.

**Comment by hannesa2** [comment]
- Espresso can't build
- Unit tests can't build
- Lint has several errors

**Comment by hannesa2** [comment]
With the missing Gradle files you even break https://jitpack.io/#videolan/vlc-android

**Pull request closed without merging**
