### PR TITLE
Fixed a typo in README .md

### PR DESCRIPTION
**Pull request by haardikdharma10**

### CODE REVIEW

**Comment by PomepuyN** [comment]
We only accept Merge requests here: https://code.videolan.org/videolan/vlc-android

BTW your fix should be `Except` and not `Expert`

**Comment by haardikdharma10** [comment]
So according to you, it should be:
**Except for translations, see the section below.**
And the section below it is 'Translations'. HOW does that make sense?
@PomepuyN

**Comment by PomepuyN** [comment]
You have to `create an account, fork vlc-android project` (...) **except** for translations. As stated below, translations are done on Transifex.

**Comment by haardikdharma10** [comment]
So you must create an account, fork vlc-android project, and propose your merge requests from it, **except** for translations. And then removing the 'see the section below' part. 
Looks good?

**Comment by MeTubeapp** [comment]
can any one help me i want to play a video from url and after video play i want to hide title which is generated by url

**Pull request closed without merging**
