### PR TITLE
More margins

### PR DESCRIPTION
**Pull request by BraisGabin**
Fix the margins as before but in the `PlaylistActivity`. I fixed the fab margins too.

### CODE REVIEW

**Comment by BraisGabin** [comment]
Please, don't merge yet. I need to check one thing.

**Comment by GeoffreyMetais** [comment]
Roger that :)

**Comment by GeoffreyMetais** [comment]
Related ticket https://code.videolan.org/videolan/vlc-android/issues/733

**Comment by BraisGabin** [comment]
Yeah, the problems posted on that ticket are the two problems not addressed in this PR. And the reason I ask to don't merge.

I kind of stuck here. The `CoordinatorLayout` does far too much magic here. `3.0.13` doesn't have this issue... I'm thinking in bisecting the issue to find the wrong commit. But I'm not sure if I'm going to be able to compile all of those.

Anyway, now that there's a issue related with the bug we can even merge this one and address that issue in other PR.

**Comment by GeoffreyMetais** [comment]
OK.

CoordinatorLayour behavior has been changed recently to hide FAB during scroll. That causes the AppBar to expand.
We just have to find a way to workaround this as SDK doesn't explicitely offer a way to lock it.

**Comment by BraisGabin** [comment]
Closing this pr. I will try to fix the problem above the next weekend but I'll open a new pr for it.

**Pull request closed without merging**
