### PR TITLE
l10n: updates

### PR DESCRIPTION
**Pull request by mtrz**
100% completed translations from Tx:
Czech, Danish, Spanish, French, Hebrew, Hungarian, Icelandic, Italian, Korean, Malay, Dutch, Slovak, Swedish, Turkish, Ukrainian, Simplified Chinese

over 90% completed translations from Tx:
Japanese, Romanian, Basque, Welsh, Croatian, Thai, Portuguese, Russian, Tatar, Norwegian Bokmål, Slovenian, Corsican

### CODE REVIEW

**Comment by GeoffreyMetais** [comment]
Could you set your full name on your github profile please? It would be easier to merge trnanslations update then :)

**Comment by GeoffreyMetais** [comment]
I couldn't merge it, because of german translation it seems.
I'll give it another try on monday.

**Comment by mtrz** [comment]
- fixed the German file, should be working now
- added Sardinian (sc) translation but might be enabled in app's languages file
- German and Polish option titles fit to the length in portrait mode now and don't be cut anymore

**Comment by GeoffreyMetais** [comment]
Merged, thanks!

**Pull request closed without merging**
